### PR TITLE
Update Composer dependencies

### LINKED ISSUE #28: sdk not compatible with guzzlehttp/guzzle 7.0.1
Installation requires one to downgrade to guzzle 6.5.5 from later versions of guzzle

### PR DESCRIPTION
**Pull request by SamuelMwangiW**
1. Bumps composer dependencies guzzlehttp/guzzle (#28)  and phpunit/phpunit to the currently supported versions 
2. Replaces deprecated assertArraySubset()
3. As a consequence of the above, the minimum php version has been bumped to 7.1

### CODE REVIEW

**Comment by coolsam726** [comment]
Someone please merge this...
I need to use the SDK on Laravel 8.

**Comment by marvinhosea** [comment]
@coolsam726 They have not merged it yet. I will try and reach out but in the meantime, you can use this one ```composer require appslabke/africastalking```

**Review by marvinhosea — APPROVED** [review]
Good

**Comment by atymic** [comment]
@calvinkarundu could you take a look at this?

**Comment by atymic** [comment]
Blocking https://github.com/laravel-notification-channels/africastalking/pull/6

**Comment by calvinkarundu** [comment]
Hey @SamuelMwangiW @atymic LGTM. We should probably publish this as a major upgrade with version `3.0.0` to avoid breaking any existing code ... let me know what you think.

**Comment by atymic** [comment]
Actually @calvinkarundu, sorry should have reviewed the PR further. We should allow either 6 or 7, like:
```
"guzzlehttp/guzzle": "^6.0 || ^7.0"
```

This way, it can not be a breaking change :)

**Comment by calvinkarundu** [comment]
No worrries @atymic ... I don't see the harm in bumping to `3.0.0` given the hard change in the minimum PHP requirement. Unless there's a substantial drawback to not implicitly shipping this to existing projects?

**Comment by atymic** [comment]
Nope, that's fine. Just as long as you allow guzzle 6 + 7 :)

**Comment by SamuelMwangiW** [comment]
> Hey @SamuelMwangiW @atymic LGTM. We should probably publish this as a major upgrade with version `3.0.0` to avoid breaking any existing code ... let me know what you think.

Hey @calvinkarundu I agree too since it introduces breaking changes for some users

**Pull request merged**
